services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PUBLIC_URL: /
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
